# enable Docker for your repository
options:
  docker: true

# Base image to run pipeline from
image: node:8.3.0

pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            # Set $IMAGE_NAME as environment variables in the pipeline settings
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t $IMAGE_NAME .
            # Set $AWS_ACCESS_KEY_ID and $AWS_SECRET_ACCESS_KEY and $AWS_DEFAULT_REGION as environment variables in the pipeline settings
            # Authenticate with aws ecr. See https://confluence.atlassian.com/bitbucket/deploy-to-aws-875304040.html
            # And examples at https://bitbucket.org/account/user/awslabs/projects/BP
            - eval $(aws ecr get-login --no-include-email --region us-east-2)
            # push the new Docker image to the ECR registry
            - docker push $IMAGE_NAME