# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
options:
  docker: true

image: node:8.3.0

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y python-dev
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
      - step:
          script: # Modify the commands below to build your repository.
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - export IMAGE_NAME=346031462502.dkr.ecr.us-east-2.amazonaws.com/abp/api:1.0
            # build the Docker image (this will use the Dockerfile in the root of the repo)
            - docker build -t $IMAGE_NAME .
            # authenticate with the Docker Hub registry
            - eval $(aws ecr get-login --no-include-email --region us-east-2)
            # - export LOGIN=$(aws ecr get-login --no-include-email --region us-east-2)
            # - $LOGIN
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME